spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: rootuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # create and destroy the schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect




#65e2fa25-b6aa-4704-bde0-d7d8ad81cd35
